<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */
function orbisius_ct_rest_abracadabra_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_rest_abracadabra_parent_style';
    $parent_base_dir = 'underscores-and-sass';

    // here we load the parent style.css
    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        wp_get_theme( $parent_base_dir ) ? wp_get_theme( $parent_base_dir )->get('Version') : ''
    );

    // here we load the child theme style.css
    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
    
    // ---> here we load the REST API JavaScript
    wp_enqueue_script( 
        'REST-js', 
        get_stylesheet_directory_uri() . '/js/js.js' 
    );
}

// ---> here the wp_enque_scripts will execute the function above
add_action( 'wp_enqueue_scripts', 'orbisius_ct_rest_abracadabra_child_theme_enqueue_styles' );
